const CHINA_STATE = [
  { value: '', label: '- Select -' },
  { value: 'BJ', label: 'Beijing' },
  { value: 'TJ', label: 'Tianjin' },
  { value: 'HE', label: 'Hebei' },
  { value: 'SX', label: 'Shanxi' },
  { value: 'NM', label: 'Inner Mongolia' },
  { value: 'LN', label: 'Liaoning' },
  { value: 'JL', label: 'Jilin' },
  { value: 'HL', label: 'Heilongjiang' },
  { value: 'SH', label: 'Shanghai' },
  { value: 'JS', label: 'Jiangsu' },
  { value: 'ZJ', label: 'Zhejiang' },
  { value: 'AH', label: 'Anhui' },
  { value: 'FJ', label: 'Fujian' },
  { value: 'JX', label: 'Jiangxi' },
  { value: 'SD', label: 'Shandong' },
  { value: 'HA', label: 'Henan' },
  { value: 'HB', label: 'Hubei' },
  { value: 'HN', label: 'Hunan' },
  { value: 'GD', label: 'Guangdong' },
  { value: 'GX', label: 'Guangxi' },
  { value: 'HI', label: 'Hainan' },
  { value: 'CQ', label: 'Chongqing' },
  { value: 'SC', label: 'Sichuan' },
  { value: 'GZ', label: 'Guizhou' },
  { value: 'YN', label: 'Yunnan' },
  { value: 'XZ', label: 'Tibet' },
  { value: 'SN', label: 'Shaanxi' },
  { value: 'GS', label: 'Gansu' },
  { value: 'QH', label: 'Qinghai' },
  { value: 'NX', label: 'Ningxia' },
  { value: 'XJ', label: 'Xinjiang' }
];

export default CHINA_STATE;