const JAPAN_PREFECTURES = [
  { value: '', label: '- Select -' },
  { value: '01', label: 'Hokkaido' },
  { value: '02', label: 'Aomori' },
  { value: '03', label: 'Iwate' },
  { value: '04', label: 'Miyagi' },
  { value: '05', label: 'Akita' },
  { value: '06', label: 'Yamagata' },
  { value: '07', label: 'Fukushima' },
  { value: '08', label: 'Ibaraki' },
  { value: '09', label: 'Tochigi' },
  { value: '10', label: 'Gunma' },
  { value: '11', label: 'Saitama' },
  { value: '12', label: 'Chiba' },
  { value: '13', label: 'Tokyo' },
  { value: '14', label: 'Kanagawa' },
  { value: '15', label: 'Niigata' },
  { value: '16', label: 'Toyama' },
  { value: '17', label: 'Ishikawa' },
  { value: '18', label: 'Fukui' },
  { value: '19', label: 'Yamanashi' },
  { value: '20', label: 'Nagano' },
  { value: '21', label: 'Gifu' },
  { value: '22', label: 'Shizuoka' },
  { value: '23', label: 'Aichi' },
  { value: '24', label: 'Mie' },
  { value: '25', label: 'Shiga' },
  { value: '26', label: 'Kyoto' },
  { value: '27', label: 'Osaka' },
  { value: '28', label: 'Hyogo' },
  { value: '29', label: 'Nara' },
  { value: '30', label: 'Wakayama' },
  { value: '31', label: 'Tottori' },
  { value: '32', label: 'Shimane' },
  { value: '33', label: 'Okayama' },
  { value: '34', label: 'Hiroshima' },
  { value: '35', label: 'Yamaguchi' },
  { value: '36', label: 'Tokushima' },
  { value: '37', label: 'Kagawa' },
  { value: '38', label: 'Ehime' },
  { value: '39', label: 'Kochi' },
  { value: '40', label: 'Fukuoka' },
  { value: '41', label: 'Saga' },
  { value: '42', label: 'Nagasaki' },
  { value: '43', label: 'Kumamoto' },
  { value: '44', label: 'Oita' },
  { value: '45', label: 'Miyazaki' },
  { value: '46', label: 'Kagoshima' },
  { value: '47', label: 'Okinawa' }
];

export default JAPAN_PREFECTURES;